[mypy]
ignore_missing_imports = True
disable_error_code = union-attr, arg-type, return-value, assignment, var-annotated, typeddict-item, attr-defined, operator, index

# We disable some strict type checks temporarily to allow the CI to pass
# while the legacy codebase is incrementally updated to strict typing.
